### ISSUE TITLE
Feature Request: Introduces the concept of "actions"

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#465]
### Is your feature request related to a problem?

This is an important feature request, discussed with @lemeurherve, to upgrade the object of type `pullRequest` to meet the following goals for end users:

- Solve the "SCM/Local" problem (#262) once for all
- Make the `pullRequest` concept not tied to GitHub (e.g. allows to use "pure Git", but would also make it compliant with GitLab or Mercurial or any other tool not using the wording "Pull Request")
- Allowing to choose wether or not to squash the commits resulting of multiple targets

We would want these 3 elements solved without too much major breaking change of course, in an expressive way allowing to keep all existing use cases.

### Solution you'd like

Example of syntax that we are proposing to evolve the actual (0.18.x):

```yaml
## No changes for scms/sources/conditions
title: "Bump LDAP Helm Chart Version"
scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"
sources:
  lastChartVersion:
    kind: helmChart
    spec:
      url: https://jenkins-infra.github.io/helm-charts
      name: ldap

## Changes for targets: no more scm/scmID concept by default, see below
targets:
  updateChartVersion:
    name: "Update the chart version for ldap"
    kind: file
    spec:
      file: clusters/prodpublick8s.yaml
      matchPattern: 'chart: jenkins-infra\/ldap((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: jenkins-infra/ldap${1}version: {{ source `lastChartVersion` }}'

## Changes: pullrequest renamed to "actions" (naming is subject to debate, see below)
actions:
  default:
    # New kind of plugin, extending actions, see below
    kind: github-pullrequest
    scmID: default
    targets:
      - updateChartVersion
    spec:
      labels:
        - dependencies
        - ldap
```

```shell
## No change: test source -> condition -> target, with dry run for targets
$ updatecli diff --config manifest.yaml --values values.yaml

## New flag that ensures that the target is applied locally but the "actions" are not applied
$ updatecli apply --config manifest.yaml --values values.yaml --no-actions # Or --actions=false

## No change: Apply all, as before
$ updatecli apply --config manifest.yaml --values values.yaml
```

For end users, it changes the following configuration items:

- Changing the naming `pullRequests` to `actions`:
  - Rationale is that "Pull Request" is a GitHub concept only. This object does not allow to express a git push, or a potential GitLab Merge Request, or even a potential "SVN commit".
  - Name is subject to discussion: Initially @lemeurherve also proposed `results` and I also proposed `destinations`. As soon as it it clears that it is the last action of a pipeline, after targets

- Targets does not have an `scmID`  (neither `scm`) by default: it is considered as a change which delegates everything related to SCM to the `actions` (see implementation details below).
  - The `scmID` attributes has to be moved under the `spec` for plugins that **requires** a SCM such as `gittag` (of course). There is not a lot so it's a minor change to these plugins, and it will improve their expressivity
  - The case of "target that change a file on a remote repository **different** than the current repo." is still supported: you have to create a 2nd object `action` that lists this target (see example collasped below).
  - To help end users, the warning when detecting a target would manage 2 cases: if the (deprecated) scmID points to the same as the action object, then tells user "maybe you just want to remove the key". If it is a different, then "perhaps you want to move it to spec".

<details>
  <summary>Click to see the example!</summary>

```yaml
# 2 SCMs defined: current and the other one name `secondary`
scms:
  default:
    # ...
  secondary:
    # ...

# sources/conditions/title as usual

targets:
  # Change version in local file ./local.version
  changeLocalConfig:
    kind: file
    sourceID: lastVersion
    spec:
      file: local.version
  # Change documentation on remote repository (see actions)
  changeRemoteDoc:
    kind: file
    sourceID: lastVersion
    spec:
      file: docs/app.adoc
      matchPattern: "^version=.*"
      replacePattern: "version={{ source `lastVersion`}}"

actions:
  default:
    kind: github-pullrequest
    scmID: default
    targets:
      - changeLocalConfig
  documentation:
    kind: github-pullrequest
    scmID: secondary
    targets:
      - changeRemoteDoc
```

</details>

- Kind of `actions`: the means defining dedicated plugins that allow different use cases (naming are subject to debate, but must be different than SCMs plugin names). Proposed plugins:
  - `local` or `none`: do not do nothing once the targets have been run. Default when no `actions` are defined.
  - (new) `git-commit`: only commit after the targets have run. Allow atomic changes (1 commit per target) or squashed
  - (new) `git-push`: commit and push after the targets have run. Allow atomic changes (1 commit per target) or squashed
  - (existing) `github-pullrequest`: commit, push and try to open a GitHub Pull Request. Allow atomic changes (1 commit per target) or squashed, but also adding labels (and maybe further features)
  - (future: not to be done today): `gitlab-mergrequest`, `gitea-pullrequest` , etc.

<details>
  <summary>Click to see the example!</summary>

```yaml
actions:
  # Do nothing
  default:
    kind: local 
  # 1 git Commit per target on defined SCM "default"
  localCommit:
    kind: git-commit
    scmID: default
    targets:
      - updateA
      - updateB
    spec:
      changes: atomic # default if not specified
  # Squashed commits, git pushed to a Gitea instance
  pushButNotToGitHub:
    kind: git-push
    scmID: gitea
    targets:
      - updateA
      - updateB
    spec:
      changes: squashed
  # Open a PR in GitHub, with only the updateA target
  github:
    kind: github-pullrequest
    scmID: github
    targets:
      - updateA
    # No spec: no labels, no squashing
```

</details>

### Anything else?

A note about implementation:

- The `PullRequest` object should be renamed to `Result` (or whatever other name we choose).
- This object should have an interface with 2 methods:
  - `RunTarget()`
  - `Run()`
- All the SCM logic must be moved away from the Target object
- It means that the pipeline execution would *looks like* the following:

```golang
# Run all the target logic
for id, t in := range config["targets"] {
  # Run Target Logic
  t.Run()
}

# THEN run all the actions-related logic for targets:
for id, t in := range config["targets"] {
  for _, r in := range config["actions"] {
    if r.targets.contains(t) {
      r.RunTarget(t)
    }
}

# Finally run the actions logic:
for _, r in := range config["actions"] {
  r.Run()
}
```

## TODO 

* [x] Rename `pullRequest` to `actions`
* [x] Create a package for the plugin github/pullrequest of kind `actions` @dduportal
* [ ] Create a package for the plugin `none` of kind `actions` and set it as default @dduportal 
* [ ] Move the "Target SCM" logic to `actions` package and add the `RunTarget()` method @dduportal 
* [ ] Add the "squash" ability (depends on SCM logic moved to `actions`)
* [ ] Move `scmID` under `spec:` for plugin that still need it
* [ ] Introduces the flag for `no actions`
* [ ] Cleanup dead/unused code (scmId on resources, etc.)

**Comment by lemeurherve** [comment]
I think "<b>actions</b>" fit lexically better with "sources", "conditions" and "targets" than "<b/>results</b>", which as you said @dduportal can also be confused with the "result" code returned by the cli.

**Comment by olblak** [comment]
Thanks, @dduportal, and @lemeurherve for taking the time to write this.
I think that I would be more in favor of the name "action".

For the different kinds, what do you think to use "/" in value such as following example:

* "github/pullrequest"
* "github/git/push"
* "github/git/commit"
* "gittea/pullrequest"
...

**Comment by dduportal** [comment]
> Thanks, @dduportal, and @lemeurherve for taking the time to write this. I think that I would be more in favor of the name "action".

Good, thanks for the feedback. Let me edit the PR title + content to materialize the "actions" naming.

> 
> For the different kinds, what do you think to use "/" in value such as following example:
> 
>     * "github/pullrequest"
> 
>     * "github/git/push"
> 
>     * "github/git/commit"
> 
>     * "gittea/pullrequest"
>       ...

Yep, looks good to me, except that it would be

- `github/pullrequest`
- `git/push` (no github)
- `git/commit` (no github)
- `gittea/pullrequest`

sounds good to you @olblak ?

**Comment by dduportal** [comment]
Updated the initial message to use the wording `actions`

**Comment by dduportal** [comment]
Proposal of a battle plan to tackle this issue. The idea is to avoid a "big" PR:

<img src="https://user-images.githubusercontent.com/1522731/149637339-ab2c90b4-08ed-47a2-95b0-9aecf9aa0733.png" alt="merge-big-branch" width="300"/>

We can tackle the following elements in independant PRs:

* Rename `pullRequest` to `actions`
* Create a package for the plugin github/pullrequest of kind `actions`
* Create a package for the plugin `none` of kind `actions` and set it as default
* Move the "Target SCM" logic to `actions` package and add the `RunTarget()` method
* Add the "squash" ability (depends on SCM logic moved to `actions`)
* Move `scmID` under `spec:` for plugin that still need it
* Introduces the flag for `no actions`
* Cleanup dead/unused code (scmId on resources, etc.)

We can start these PRs as soon as we want.

WDYT?

**Comment by lemeurherve** [comment]
I'd also like to talk out loud to you and @olblak about a complementary concept, "subjects" (relative to composition, templating, and potential simplification of manifests, will develop later)

**Comment by olblak** [comment]
To handle the local git repository, I am wondering if it would make sense to have a specific scm resource kind named `local`. It would also be available where default values can be overridden such as in the following example.
```
## No changes for scms/sources/conditions
title: "Bump LDAP Helm Chart Version"
scms:
  # Local is a specific scm resource which can only be used with the kind **"local"**
  # And it always exist with default value but could be overridden with some settings 
  # The only parameter that I can think of is directory
  local: 
    kind: local 
    spec:
        directory: "~/projects/example"

## Changes for targets: no more scm/scmID concept by default, see below
targets:
  updateChartVersion:
    name: "Update the chart version for ldap"
    kind: file
    spec:
      file: clusters/prodpublick8s.yaml
      matchPattern: 'chart: jenkins-infra\/ldap((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: jenkins-infra/ldap${1}version: {{ source `lastChartVersion` }}'

## Changes: pullrequest renamed to "actions" (naming is subject to debate, see below)
actions:
  default:
    # New kind of plugin, extending actions, see below
    kind: github-pullrequest
    scmid: local
    targets:
      - updateChartVersion
    spec:
      labels:
        - dependencies
        - ldap
```

@dduportal If it makes sense to you,  this could be one of the next think I could implement

**Comment by dduportal** [comment]
@olblak that makes sense! I wonder about the naming: `local`, `default`, `auto` ?

**Comment by dduportal** [comment]
> To handle the local git repository, I am wondering if it would make sense to have a specific scm resource kind named `local`. It would always be available with default values. Those default values could be overridden using the scms key such as in the following example.
> 
> ```
> ## No changes for scms/sources/conditions
> title: "Bump LDAP Helm Chart Version"
> scms:
>   # Local is a specific scm resource which can only be used with the kind **"local"**
>   # And it always exist with default value but could be overridden with some settings 
>   # The only parameter that I can think of is directory
>   local: 
>     kind: local 
>     spec:
>         directory: "~/projects/example"
> 
> ## Changes for targets: no more scm/scmID concept by default, see below
> targets:
>   updateChartVersion:
>     name: "Update the chart version for ldap"
>     kind: file
>     spec:
>       file: clusters/prodpublick8s.yaml
>       matchPattern: 'chart: jenkins-infra\/ldap((\r\n|\r|\n)(\s+))version: .*'
>       replacePattern: 'chart: jenkins-infra/ldap${1}version: {{ source `lastChartVersion` }}'
> 
> ## Changes: pullrequest renamed to "actions" (naming is subject to debate, see below)
> actions:
>   default:
>     # New kind of plugin, extending actions, see below
>     kind: github-pullrequest
>     scmid: local
>     targets:
>       - updateChartVersion
>     spec:
>       labels:
>         - dependencies
>         - ldap
> ```
> 
> @dduportal If it makes sense to you, this could be one of the next think I could implement

I'm gonna go for a first PR for this initial idea, but without the "kind local" stuff. i'll stay with the actual definitions:

- Reserving the name `local` for the `scms` list
- If there is not any SCM  name `local`, then updatecli tries to auto-fill it based on its environment (check if there is a git/github repository defined in the current working dir, extract the remote name if yes, and determine the type)
- If a SCM named `local` is defined, then it means that the end-user explicitely takes control and defines the values themselves
  - In the case of only partial values defined for this SCM, then `updatecli` will try to guess the `local` values, and then will override the specific values provided by the end user
  - If the value `scms.local.disable` is set to `true` (default is `false`) , then no automatic guessing


Examples:

*  No SCM: guessing by default (user can refer to the SCM `local`):

```yaml
title: "Bump LDAP Helm Chart Version"

# ... sources/conditions here

targets:
  updateChartVersion:
    name: "Update the chart version for ldap"
    kind: file
    spec:
      file: clusters/prodpublick8s.yaml
      matchPattern: 'chart: jenkins-infra\/ldap((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: jenkins-infra/ldap${1}version: {{ source `lastChartVersion` }}'
    scmid: local

pullrequests:
  default:
    kind: github
    scmid: local
    targets:
      - updateChartVersion
    spec:
      labels:
        - dependencies
        - ldap
```

* Disabled `local` SCM. Any tentative to refer to it would throw an error (e.g. `scmid: local` exits in error in this case)

```yaml
title: "Bump LDAP Helm Chart Version"

scms:
  local:
    disabled: true
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

targets:
  updateChartVersion:
    name: "Update the chart version for ldap"
    kind: file
    spec:
      file: clusters/prodpublick8s.yaml
      matchPattern: 'chart: jenkins-infra\/ldap((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: jenkins-infra/ldap${1}version: {{ source `lastChartVersion` }}'
    scmid: default

pullrequests:
  default:
    kind: github
    scmid: default
    targets:
      - updateChartVersion
    spec:
      labels:
        - dependencies
        - ldap
```

* End user specifies "partially" the `local` SCM:

```yaml
title: "Bump LDAP Helm Chart Version"

scms:
  local:
    kind: github # Mandatory, helps to guess
    spec:
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"

targets:
  updateChartVersion:
    name: "Update the chart version for ldap"
    kind: file
    spec:
      file: clusters/prodpublick8s.yaml
      matchPattern: 'chart: jenkins-infra\/ldap((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: jenkins-infra/ldap${1}version: {{ source `lastChartVersion` }}'
    scmid: local

pullrequests:
  default:
    kind: github
    scmid: local
    targets:
      - updateChartVersion
    spec:
      labels:
        - dependencies
        - ldap
```


* End user specifies ALL the `local` SCM (same as previous in reality, except there are more overridden values):

```yaml
title: "Bump LDAP Helm Chart Version"

scms:
  local:
    kind: github # Mandatory, helps to guess
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

targets:
  updateChartVersion:
    name: "Update the chart version for ldap"
    kind: file
    spec:
      file: clusters/prodpublick8s.yaml
      matchPattern: 'chart: jenkins-infra\/ldap((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: jenkins-infra/ldap${1}version: {{ source `lastChartVersion` }}'
    scmid: local

pullrequests:
  default:
    kind: github
    scmid: local
    targets:
      - updateChartVersion
    spec:
      labels:
        - dependencies
        - ldap
 ```

**Comment by lemeurherve** [comment]
> * If a SCM named `local` is defined, then it means that the end-user explicitely takes control and defines the values themselves

WDYT of `manual` instead of `local` in this case?

**Comment by dduportal** [comment]
> > * If a SCM named `local` is defined, then it means that the end-user explicitely takes control and defines the values themselves
> 
> WDYT of `manual` instead of `local` in that case?

I'm not sure to understand the meaning of `manual` in this case?

**Comment by lemeurherve** [comment]
Explicit manual: user control?
If not apparent for you it means it's not what's expected, forget about it :)

**Comment by olblak** [comment]
"manul" doesn't feel natural to me, I think "local" or "default" it makes more sense to me

**Comment by dduportal** [comment]
Opened https://github.com/updatecli/updatecli/issues/716 for the feature "local" SCM

**Comment by dduportal** [comment]
Now that #990 was merged, next steps:

- Experiment with https://github.com/updatecli/updatecli/pull/1030. Closed because it needs other changes (see below) and some hypothesis changed.
- Factorization of the actions into their own package is now required:
  - Simplify the code of the SCM plugins (only focus on implement API related action)
  - Clarify the role of actions, since it was renamed, it is in a weird state now. (Change `CreateAction()` to `Run()` and maybe more)
  - Prepare the next iteration related to targets in diff/apply (requires at least a `RunTarget()`)
- New features out of these upcoming changes:
  - Action of type `git/commit`
  - Action of type `git/branch`
  - Action of type `git/push`

**Comment by dduportal** [comment]
Closing as the actions have been there for quite some time, and we need a cleared path to define the next steps:

- New actions type? (`git/email`, etc.)
- Removing SCM logic out from targets ?
- Running on local paths (or not) ?
etc.
